<?php

/**
 * @file
 * Handles the form validation of the customer survey form
 * All hooks are in the .module file.
 */


/**
 * Master validation function for the customer survey form - uses per-stage 
 * validation and calls functions for each one.
 * 
 * @param type $form
 * @param type $form_state
 * @return type 
 */
function customer_survey_form_validate($form, &$form_state) {

}
function customer_survey_rate_the_room_validate($form, &$form_state) {
 
}
function customer_survey_rate_the_service_validate($form, &$form_state) {
 
}

function customer_survey_personal_details_validate($form, &$form_state) {
  
  
  
}
